config/routes.rb
Rails.application.routes.draw do
  resources :bosses

  resources :people

  get 'bosses/index' => 'bosses#index'
  root 'mains#index'

  resources :people

  get 'people' => 'people#index'
  get 'people/index' => 'people#index'
  get 'people/new' => 'people#create'
  patch 'people/:id' => 'people#update'
  delete 'people/:id' => 'people#destroy'

end

app/models/boss.rb
class Boss < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveResource::Base
  self.site = "http://104.236.240.116"
  self.element_name = 'person'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bosses_controller.rb
class BossesController < ApplicationController
  before_action :set_boss, only: [:show, :edit, :update, :destroy]

  # GET /bosses
  # GET /bosses.json
  def index
    @bosses = Boss.all
  end

  # GET /bosses/1
  # GET /bosses/1.json
  def show
  end

  # GET /bosses/new
  def new
    @boss = Boss.new
  end

  # GET /bosses/1/edit
  def edit
  end

  # POST /bosses
  # POST /bosses.json
  def create
    @boss = Boss.new(boss_params)

    respond_to do |format|
      if @boss.save
        format.html { redirect_to @boss, notice: 'Boss was successfully created.' }
        format.json { render :show, status: :created, location: @boss }
      else
        format.html { render :new }
        format.json { render json: @boss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bosses/1
  # PATCH/PUT /bosses/1.json
  def update
    respond_to do |format|
      if @boss.update(boss_params)
        format.html { redirect_to @boss, notice: 'Boss was successfully updated.' }
        format.json { render :show, status: :ok, location: @boss }
      else
        format.html { render :edit }
        format.json { render json: @boss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bosses/1
  # DELETE /bosses/1.json
  def destroy
    @boss.destroy
    respond_to do |format|
      format.html { redirect_to bosses_url, notice: 'Boss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boss
      @boss = Boss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boss_params
      params.require(:boss).permit(:name)
    end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
    @people = Person.all
  end


  def new
    # GET /people/new
   # @person = Person.new
   #@person = Person.new(:name => 'GAH2')
   @person = Person.new(:name => '')
   # @person = Person.new(person_params)
  end

  def edit
    # GET /people/1/edit
    @person = Person.find(params[:id])
  end

  def create
    # POST /people
   #@person = Person.new(:name => 'GAH2')
   @person = Person.new(person_params)
    respond_to do |format|

      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update_attributes(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.

  def person_params
    params.require(:person).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bosses_helper.rb
module BossesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/bosses/_form.html.erb
<%= form_for(@boss) do |f| %>
  <% if @boss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boss.errors.count, "error") %> prohibited this boss from being saved:</h2>

      <ul>
      <% @boss.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bosses/edit.html.erb
<h1>Editing Boss</h1>

<%= render 'form' %>

<%= link_to 'Show', @boss %> |
<%= link_to 'Back', bosses_path %>

app/views/bosses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Bosses names from local machine.</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bosses.each do |boss| %>
      <tr>
        <td><%= boss.name %></td>
        <td><%= link_to 'Show', boss %></td>
        <td><%= link_to 'Edit', edit_boss_path(boss) %></td>
        <td><%= link_to 'Destroy', boss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Boss', new_boss_path %>

app/views/bosses/new.html.erb
<h1>New Boss</h1>

<%= render 'form' %>

<%= link_to 'Back', bosses_path %>

app/views/bosses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @boss.name %>
</p>

<%= link_to 'Edit', edit_boss_path(@boss) %> |
<%= link_to 'Back', bosses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webservice Homework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Gregory Hambrick's Webservice homework app", root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
      </ul>
    </nav>
  </div>
</header>
<div class="container">

</div>

<%= yield %>

</body>
</html>

app/views/mains/_form.html.erb
<%= form_for(@main) do |f| %>
  <% if @main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
      <% @main.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mains/edit.html.erb
<h1>Editing Main</h1>

<%= render 'form' %>

<%= link_to 'Show', @main %> |
<%= link_to 'Back', mains_path %>

app/views/mains/index.html.erb
<h2>Main Webservice Page</h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <p>My Rails web app has a local component, "My People"  and a remote Webserivce Component "Your People".</p>

        <p>People Pages</p>

        <a href="http://localhost:3000/bosses">My People - Local</a>
        <p><a href="http://localhost:3000/people">Your People - Remote</a></p>

      </tr>

  </tbody>
</table>

app/views/mains/new.html.erb
<h1>New Main</h1>

<%= render 'form' %>

<%= link_to 'Back', mains_path %>

app/views/mains/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_main_path(@main) %> |
<%= link_to 'Back', mains_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List People from remote website</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>Enter a New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Now Viewing Name:</strong>
  <%= @person.name %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>